### ISSUE TITLE
Does anyone are having errors from Box API this February 2020?

### ISSUE THREAD

**Issue by ecuation** [maengkom/boxapi#25]
I can't find the error, but seems like Box made an update or something that makes some requests break. Sometimes its like the generated token to authenticate to Box is not recognized as a recent and valid token. Anyone with this same issue?

**Comment by kaypro4** [comment]
Hello, we've been seeing intermittent token issues in the last couple weeks too. It seems to be a result of the getToken method failing to be issued a token in some cases. I debugged by just outputting the $result value to the screen. It was showing a 302 redirect so I updated the curl command with -L to have it follow the redirect which resulted in me seeing the actual error message. 

Here it is:

`{"error":"invalid_request","error_description":"Invalid grant_type parameter or parameter missing"}`

I'm baffled at this point, but will keep debugging. Please let me know if you run across any leads.

**Comment by kaypro4** [comment]
@ecuation I got a suggestion from Box support to replace https://www.box.com/api/oauth2/token in BoxAppUser.php (set as $token_url) with https://api.box.com/oauth2/token. 

I did this and then ran through about 20 requests and got a token every time and no errors. 

https://community.box.com/t5/Platform-and-Development-Forum/Intermittent-quot-invalid-request-quot-when-requesting-token/m-p/81797/highlight/false#M7744

Followed up with Box support to see if there was a recent change that may have caused this. Anyway, hope this solves your issue as well.

**Comment by ecuation** [comment]
Hi @kaypro4 I just read your last messages. Finally seems like that is the solution, I got but I don't know how... I was that day working more than 12 hours trying to find a fix and also Box didn't gave me a solution. So if someone else experiences that annoying issue, yes, that is the solution. Thanks!
