### ISSUE TITLE
php artisan publish vendor:publish --provider="Maengkom/Box/BoxAPIServiceProvider"

### ISSUE THREAD

**Issue by cherbert** [maengkom/boxapi#5]
When typing this command...

php artisan publish vendor:publish --provider="Maengkom/Box/BoxAPIServiceProvider"

I get an exception error. I assume you mean... 

php artisan vendor:publish --provider="Maengkom/Box/BoxAPIServiceProvider"

But that doesn't work either. I get 'Nothing to publish for tag [].'

**Comment by maengkom** [comment]
You are correct, I mistype the artisan command. I will check and back soon. Thanks for info.

**Comment by maengkom** [comment]
Hello, you may use this command 

    php artisan vendor:publish --tag="boxapi"
