### ISSUE TITLE
Trying new PM

### ISSUE THREAD

**Issue by maengkom** [maengkom/boxapi#7]
Get to go from here....

**Comment by maengkom** [comment]
Testing comment

**Comment by sureshwininfo** [comment]
Hi maengkom,

I am trying to integrate box api in laravel but i am not able to auth box app so please can you help me what mistak i do there.

**Comment by maengkom** [comment]
Hi @sureshwininfo, what version of laravel do you use ? I'll try to check. Please create new issue, I'll close this.

**Comment by sureshwininfo** [comment]
I am using laravel 5.2 version.

**Comment by sureshwininfo** [comment]
use BoxSU;
After Above I Call Below Method
$boxInfo = BoxSU::getFolderInfo('0', true);

**Comment by maengkom** [comment]
If error of stat filesize : try to update package or update your exising code with this little bit fix  https://github.com/maengkom/boxapi/commit/12b647fdd0f4b521de5a12bdc3c3f49ced2d1b95

If other error, may be your configuration. Get client id, client secret and set redirect url in https
![image](https://cloud.githubusercontent.com/assets/960467/21748775/32f6fd3c-d5c0-11e6-8689-fd5966dd5161.png)

And open config/boxapi.php and set it those values for `su_client_id`, `su_client_secret`, and `redirect_uri`. Done you can use box standard user.

**Comment by sureshwininfo** [comment]
Okay Thanks For Your Support But I am Not Success Because I am Call This API In My Local System And Setup Setting Like As Your Give In Help.

**Comment by sureshwininfo** [comment]
![box](https://cloud.githubusercontent.com/assets/19724284/21758616/7cd105ee-d663-11e6-9f0c-1e07e90b7b0a.png)

**Comment by sureshwininfo** [comment]
'su_client_id'      => '4nnn7egp....',
 'su_client_secret'  => 'm00Pae0t....',
 'redirect_uri'  	=> 'http://localhost'

**Comment by sureshwininfo** [comment]
Above Is My boxapi.php file settings.
